Resources:
  # Api gateway definition with swagger
  ToDoApi:
    DependsOn:
      - ToDoUserPool
      - ToDoDB
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'Released'
      Name:
        Fn::Sub: '${StageName}-todo-app'
      Auth:
        Authorizers:
          ToDoCognitoAuthorizer:
            UserPoolArn:
              Fn::Sub: '${ToDoUserPool.Arn}'
      DefinitionBody:
        $include: ./api.yaml