Resources:
  # Api gateway definition with swagger
  ToDoApi:
    DependsOn:
      - AuthorizationFunction
      - ToDoDB
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'Released'
      Name:
        Fn::Sub: '${StageName}-todo-app'
      Auth:
        DefaultAuthorizer: ToDoLambdaAuthorizer
        Authorizers:
          ToDoLambdaAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn:
              Fn::Sub: '${AuthorizationFunction.Arn}'
      DefinitionBody:
        $include: ./api.yaml