Function:
  Runtime: nodejs8.10
  VpcConfig:
    SecurityGroupIds:
      - Ref: LambdaSecurityGroup
    SubnetIds:
      - Ref: PrivateSubnet1
      - Ref: PrivateSubnet2
      - Ref: PrivateSubnet3
  Environment:
    Variables:
      # TODO: add cognito access
      DB_HOST:
        Fn::GetAtt: ToDoDB.Endpoint.Address
      DB_USER:
        Ref: DBUser
      DB_PASSWORD:
        Ref: DBPassword
      DB_NAME:
        Ref: DBName
      S3_PUBLIC_DATA:
        Ref: DataS3BucketName
      DEPLOYMENT_REGION:
        Ref: AWS::Region
      SQS_MAIL_URL:
        Ref: MialSQS