DBUser:
  Type: String
  NoEcho: true
  Description: 'your db user'
  MinLength: 1
  MaxLength: 16
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ConstraintDescription: 'Must begin with a letter and contain only alphanumeric characters.'
DBName:
  Type: String
  Description: 'your db name'
  MinLength: 1
  MaxLength: 64
  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  ConstraintDescription: 'Must begin with a letter and contain only alphanumeric characters.'
DBPassword:
  Type: String
  NoEcho: true
  Description: 'your db password'
  MinLength: 8
  MaxLength: 41
  AllowedPattern: '[a-zA-Z0-9]*'
  ConstraintDescription: 'Must contain only alphanumeric characters.'
