AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  todo-example-app
  Users SAM Template for Todo app


Parameters:
  # deploy settings
  StageName:
    Type: String
    Description: 'Application stage to deploy e.g. dev, test, production'
    Default: 'dev'
  # network settings
  LambdaSecurityGroup:
    Type: String
    Description: 'Lambda Security Group'
  PrivateSubnet1:
    Type: String
    Description: 'Private Subnet 1'
  PrivateSubnet2:
    Type: String
    Description: 'Private Subnet 2'
  PrivateSubnet3:
    Type: String
    Description: 'Private Subnet 3'
  # db configuration
  DBName:
    Type: String
    Description: 'your db name'
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: 'Must begin with a letter and contain only alphanumeric characters.'
  DBUser:
    Type: String
    NoEcho: true
    Description: 'your db user'
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: 'Must begin with a letter and contain only alphanumeric characters.'
  DBPassword:
    Type: String
    NoEcho: true
    Description: 'your db password'
    MinLength: 8
    MaxLength: 41
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: 'Must contain only alphanumeric characters.'
  TodoDBEndpointAddress:
    Type: String
    Description: 'Todo DB Endpoint Address'
  # auth
  AuthorizationFunctionArn:
    Type: String
    Description: 'Authorization Function Arn'
  # mail
  MailSQS:
    Type: String
    Description: 'Mail SQS ref'
  # s3
  DataS3BucketName:
    Type: String
    Description: 'S3 bucket foe data saved by users'
  # pass
  PassSalt:
    Type: String
    NoEcho: true
    Description: 'Sald for password'
    Default: 'WQDI5MS2OS4DJAQ1RWZL'
  # node dependencies
  MainDependenciesLayer:
    Type: String
    Description: 'Todo layers with node dependencies'
Outputs:
  EditUserRole:
    Value:
      Ref: EditUserRole
  DeleteUserRole:
    Value:
      Ref: DeleteUserRole
Globals:
  Function:
    Runtime: nodejs10.x
    VpcConfig:
      SecurityGroupIds:
        - Ref: LambdaSecurityGroup
      SubnetIds:
        - Ref: PrivateSubnet1
        - Ref: PrivateSubnet2
        - Ref: PrivateSubnet3
    Environment:
      Variables:
        DB_HOST:
          Ref: TodoDBEndpointAddress
        DB_USER:
          Ref: DBUser
        DB_PASSWORD:
          Ref: DBPassword
        DB_NAME:
          Ref: DBName
        STAGE:
          Ref: StageName
        S3_PUBLIC_DATA:
          Ref: DataS3BucketName
        SQS_MAIL_URL:
          Ref: MailSQS
        SALT:
          Ref: PassSalt