Resources:
  EditToDoListRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: '${StageName}-edit-todo-list-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  EditToDoListFunction:
    Type: AWS::Serverless::Function
    Name:
      Fn::Sub: '${StageName}-edit-todo-list'
    Properties:
      Role:
        Fn::Sub: '${EditToDoListRole.Arn}'
      CodeUri: ./src
      Handler: actions/todo_list/edit.handler
      Events:
        SddFile:
          Type: Api
          Properties:
            Path: /todo_list/{listId}
            Method: put
            RestApiId:
              Ref: ToDoApi