Resources:
  DetailsTodoRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: '${StageName}-details-todo-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  DetailsTodoFunction:
    DependsOn: DetailsTodoRole
    Type: AWS::Serverless::Function
    Name:
      Fn::Sub: '${StageName}-details-todo'
    Properties:
      Role:
        Fn::Sub: '${DetailsTodoRole.Arn}'
      CodeUri: ../../../src
      Handler: actions/todo/details.handler
      Layers:
        - Ref: MainDependenciesLayer
      Events:
        ApiAction:
          Type: Api
          Properties:
            Path: /{id}
            Method: get
            RestApiId:
              Ref: ToDoApi
        KeepAlive:
          Type: Schedule
          Properties:
            Input: '{"keep_alive_request":true}'
            Schedule: rate(10 minutes)