Resources:
  VersionsTodoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'Released'
      Name:
        Fn::Sub: '${StageName}-versions-todo-app'
      DefinitionBody:
        $include: ./api.yaml