Resources:
  # Cognito Configuration
  ToDoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Fn::Sub: '${StageName}-todo-userpool'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: 'email'
          Required: false
  # pool id and key to env