AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:  >
  todo-app
  Main SAM Template for Todo app

Parameters:
  StageName:
    Type: String
    Description: 'Application stage to deploy e.g. dev, test, production'
    Default: dev
Outputs:
  MainDependenciesLayer:
    Value:
      Ref: MainDependenciesLayer
  MigrationsDependenciesLayer:
    Value:
      Ref: MigrationsDependenciesLayer
Resources:
  MainDependenciesLayer:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      ContentUri: ../../layers/main
      LayerName:
        Fn::Sub: '${StageName}-main-dependencies-layer'
      LicenseInfo: MIT
      CompatibleRuntimes:
        - nodejs10.x
  MigrationsDependenciesLayer:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      ContentUri: ../../layers/migrations
      LayerName:
        Fn::Sub: '${StageName}-migrations-dependencies-layer'
      LicenseInfo: MIT
      CompatibleRuntimes:
        - nodejs10.x