Resources:
  # Security Groups
  LambdaSecurityGroup:
    DependsOn:
      - PrivateSubnet1RouteTableAssociation
      - PrivateSubnet2RouteTableAssociation
      - PrivateSubnet3RouteTableAssociation
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Lambda security group'
      VpcId:
        Ref: MainVPC
  RDSSecurityGroup:
    DependsOn: LambdaSecurityGroup
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'RDS security group'
      VpcId:
        Ref: MainVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId:
            Ref: LambdaSecurityGroup