Resources:
  DeleteFileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: '${StageName}-delete-file-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  DeleteFileFunction:
    DependsOn: DeleteFileRole
    Type: AWS::Serverless::Function
    Name:
      Fn::Sub: '${StageName}-delete-file'
    Properties:
      Role:
        Fn::Sub: '${DeleteFileRole.Arn}'
      CodeUri: ../../../src
      Handler: actions/files/delete.handler
      Layers:
        - Ref: MainDependenciesLayer
      Events:
        ApiAction:
          Type: Api
          Properties:
            Path: /{id}
            Method: delete
            RestApiId:
              Ref: FilesApi
        KeepAlive:
          Type: Schedule
          Properties:
            Input: '{"keep_alive_request":true}'
            Schedule: rate(10 minutes)