swagger: '2.0'
info:
  version: '0.1'
  title: 'Users Todo API'
securityDefinitions:
  TodoLambdaAuthorizer:
    type: apiKey
    name: 'Authorization'
    in: header
    x-amazon-apigateway-authtype: custom
    x-amazon-apigateway-authorizer:
      authorizerUri:
        Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizationFunctionArn}/invocations'
      authorizerResultTtlInSeconds: 0
      type: token
definitions:
  UserProfileResponse:
    title: 'user profile response'
    type: object
    properties:
      profileData:
        type: object
      dictionaries:
        type: object
  ErrorResponse:
    title: 'error responses'
    type: object
    required:
      - errors
    properties:
      errors:
        type: object