Resources:
  RegisterUserRole:
    DependsOn: MialSQS
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: '${StageName}-register-user-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
  RegisterUserFunction:
    DependsOn: RegisterUserRole
    Type: AWS::Serverless::Function
    Name:
      Fn::Sub: '${StageName}-register-user'
    Properties:
      Role:
        Fn::Sub: '${RegisterUserRole.Arn}'
      CodeUri: ./src
      Handler: actions/auth/register.handler
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /auth/register
            Method: post
            RestApiId:
              Ref: ToDoApi