AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  todo-app
  Migrations SAM Template for Todo app

Parameters:
  # deploy settings
  StageName:
    Type: String
    Description: 'Application stage to deploy e.g. dev, test, production'
    Default: 'dev'
  DeployVersion:
    Type: String
    NoEcho: true
    Description: 'timestamp to update custom resources'
    Default: 'init'
  # db configuration
  DBName:
    Type: String
    Description: 'your db name'
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: 'Must begin with a letter and contain only alphanumeric characters.'
  DBUser:
    Type: String
    NoEcho: true
    Description: 'your db user'
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: 'Must begin with a letter and contain only alphanumeric characters.'
  DBPassword:
    Type: String
    NoEcho: true
    Description: 'your db password'
    MinLength: 8
    MaxLength: 41
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: 'Must contain only alphanumeric characters.'
  TodoDBEndpointAddress:
    Type: String
    Description: 'Todo DB Endpoint Address'
  # network settings
  LambdaSecurityGroup:
    Type: String
    Description: 'Lambda Security Group'
  PrivateSubnet1:
    Type: String
    Description: 'Private Subnet 1'
  PrivateSubnet2:
    Type: String
    Description: 'Private Subnet 2'
  PrivateSubnet3:
    Type: String
    Description: 'Private Subnet 3'
  # helpers
  PassSalt:
    Type: String
    NoEcho: true
    Description: 'Sald for password'
    Default: 'WQDI5MS2OS4DJAQ1RWZL'
  # node dependencies
  MigrationsDependenciesLayer:
    Type: String
    Description: 'Todo layers with node dependencies for migrations'
Globals:
  Function:
    Runtime: nodejs10.x
    VpcConfig:
      SecurityGroupIds:
        - Ref: LambdaSecurityGroup
      SubnetIds:
        - Ref: PrivateSubnet1
        - Ref: PrivateSubnet2
        - Ref: PrivateSubnet3
    Environment:
      Variables:
        DB_HOST:
          Ref: TodoDBEndpointAddress
        DB_USER:
          Ref: DBUser
        DB_PASSWORD:
          Ref: DBPassword
        DB_NAME:
          Ref: DBName
        SALT:
          Ref: PassSalt
        STAGE:
          Ref: StageName