swagger: '2.0'
info:
  version: '0.1'
  title: 'Todo API'
# cognito authorizer
securityDefinitions:
  ToDoCognitoAuthorizer:
    type: apiKey
    name: 'Authorization'
    in: header
    x-amazon-apigateway-authtype: cognito_user_pools
definitions:
  ErrorResponse:
    title: 'version response error'
    type: object
    required:
      - errors
    properties:
      errors:
        type: object