swagger: '2.0'
info:
  version: '0.1'
  title: 'Todo API'
# cognito authorizer
securityDefinitions:
  ToDoLambdaAuthorizer:
    type: apiKey
    name: 'Authorization'
    in: header
    x-amazon-apigateway-authtype: custom
    x-amazon-apigateway-authorizer:
      authorizerUri:
        Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizationFunction.Arn}/invocations'
      authorizerResultTtlInSeconds: 300
      type: token
definitions:
  UserResponse:
    title: 'user response'
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      status:
        type: string
  ToDoListResponse:
    title: 'user response'
    type: object
    properties:
      userId:
        type: string
      id:
        type: string
      title:
        type: string
      items:
        type: object
  ToDoResponse:
    title: 'user response'
    type: object
    properties:
      id:
        type: string
      listId:
        type: string
      description:
        type: string
      status:
        type: string
      title:
        type: string
      files:
        type: object
  ErrorResponse:
    title: 'version response error'
    type: object
    required:
      - errors
    properties:
      errors:
        type: object